redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/nobi/Projects/Libre/github/tools.libre.org/dist"
publishOrigin = "ui"
commandOrigin = "ui"
base = "/Users/nobi/Projects/Libre/github/tools.libre.org"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]